name: Typos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check spelling
        uses: crate-ci/typos@master
        with:
          # Exclude Cargo.lock and binary assets implicitly handled by typos.toml
          files: .
